"""Add frequency in MedicationRequest

Revision ID: 5ca44c30de37
Revises: 758190287fe6
Create Date: 2024-07-25 19:46:58.597989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ca44c30de37"
down_revision: Union[str, None] = "758190287fe6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medication_requests", sa.Column("frequency", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medication_requests", "frequency")
    # ### end Alembic commands ###
