"""AddCodeName in Medication

Revision ID: 758190287fe6
Revises: cc2849ba90e4
Create Date: 2024-07-25 19:20:48.684150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "758190287fe6"
down_revision: Union[str, None] = "cc2849ba90e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medications", sa.Column("code_name", sa.String(length=30), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medications", "code_name")
    # ### end Alembic commands ###
