"""AddStatusToMedicationRequest

Revision ID: cc2849ba90e4
Revises: 
Create Date: 2024-07-25 17:40:40.144975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc2849ba90e4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinicians",
        sa.Column("registration_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("registration_id"),
    )
    op.create_index(
        op.f("ix_clinicians_registration_id"),
        "clinicians",
        ["registration_id"],
        unique=False,
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("code_system", sa.String(length=30), nullable=False),
        sa.Column("strength_value", sa.Float(), nullable=False),
        sa.Column("strength_unit", sa.String(length=30), nullable=False),
        sa.Column(
            "form",
            sa.Enum("powder", "tablet", "capsule", "syrup", name="formenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("sex", sa.Enum("male", "female", name="sexenum"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_id"), "patients", ["id"], unique=False)
    op.create_table(
        "medication_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patience_id", sa.UUID(), nullable=False),
        sa.Column("clinician_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("prescribed_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "on_hold", "cancelled", "completed", name="statusenum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"], ["clinicians.registration_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"], ["medications.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["patience_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_requests_clinician_id"),
        "medication_requests",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_medication_id"),
        "medication_requests",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_patience_id"),
        "medication_requests",
        ["patience_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_medication_requests_patience_id"), table_name="medication_requests"
    )
    op.drop_index(
        op.f("ix_medication_requests_medication_id"), table_name="medication_requests"
    )
    op.drop_index(
        op.f("ix_medication_requests_clinician_id"), table_name="medication_requests"
    )
    op.drop_table("medication_requests")
    op.drop_index(op.f("ix_patients_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_table("medications")
    op.drop_index(op.f("ix_clinicians_registration_id"), table_name="clinicians")
    op.drop_table("clinicians")
    # ### end Alembic commands ###
